name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install check
        git submodule update --init --recursive
    - name: make test
      run: make test
